version: "3"

services:
  db:
    build:
      context: .
      dockerfile: ./container/db/Dockerfile
    ports:
      - 5454:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: satoruchan
    volumes:
      - satoruchan_db_data:/var/lib/postgresql/data
      - ./container/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    container_name: satoruchan_db
  web:
    build:
      context: .
      dockerfile: ./container/app/Dockerfile
    depends_on:
      - db
    tty: true
    ports:
      - 8888:8888
    environment:
      - DATABASE_URL=postgres://postgres:postgres@satoruchan_db:5432/satoruchan
      - NODE_ENV=development
    container_name: node_app
    volumes:
      - satoruchan_node_modules:/usr/src/app/node_modules
      - ./app:/usr/src/app
    command: yarn dev-tsd
volumes:
  satoruchan_db_data: {}
  satoruchan_node_modules: {}
