version: '3'

services:
  db:
    build:
      context: .
      dockerfile: ./container/db/Dockerfile
    ports:
      - 5454:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: satoruchan
    volumes:
      - satoruchan_db_data:/var/lib/postgresql/data
      - ./container/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    container_name: satoruchan_db
  app:
    build:
      context: .
      dockerfile: ./container/app/Dockerfile
    depends_on:
      - db
    tty: true
    ports:
      - 8888:8888
    environment:
      - DATABASE_URL=postgres://postgres:postgres@satoruchan_db:5432/satoruchan
    container_name: node_app
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    command: yarn dev-tsd
volumes:
  satoruchan_db_data: {}
